version: 0.2

phases:
  install:
    commands:
      - echo "Installing test dependencies..."
      - ./gradlew test  # Adjust if using npm or Maven or Java
  build:
    commands:
      - echo "Running tests..."
      - curl -v -u greg:turnquist localhost:8080/api/employees/3
            {
            "firstName" : "Frodo",
            "lastName" : "Baggins",
            "description" : "ring bearer",
            "manager" : {
            "name" : "greg",
            "roles" : [ "ROLE_MANAGER" ]
            },
            "_links" : {
            "self" : {
            "href" : "http://localhost:8080/api/employees/1"
            }
            }
            }
      
